server.port: 8101

kayttooikeus.oauth2.publickey: classpath:public_key.pem
kayttooikeus.oauth2.privatekey: classpath:private_key.pem

kayttooikeus.userdetails.enabled: false

cas.url: http://${host-cas}/cas
cas.login: http://${host-cas}/cas/login