services:
  cas:
    container_name: cas-oppija
    image: cas-oppija:latest
    ports:
     - "8444:8443"
     - "8081:8081"
    environment:
      ENV: local
      keystore_base64: ""
      sp_metadata: ""
      registered_service_1: ""
      registered_service_2: ""
      registered_service_tiedotuspalvelu: ""