name: Build and test artifacts
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run-tests-cas-oppija:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'corretto'
          java-version: '11'
      - run: ./scripts/ci/run-tests-cas-oppija.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-tests-cas-virkailija:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Helsinki
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'corretto'
          java-version: '21'
      - run: ./scripts/ci/run-tests-cas-virkailija.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-tests-kayttooikeus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'corretto'
          java-version: '21'
      - run: ./scripts/ci/run-tests-kayttooikeus.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-tests-service-provider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'corretto'
          java-version: '21'
      - run: ./scripts/ci/run-tests-service-provider.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}